### ISSUE TITLE
Please add license

### ISSUE THREAD

**Issue by mekhanique** [drpebcak/ollama-provider#2]
I’d love to use this on my local workstation for work purposes.  To do that, the project  must have a license in the repo.  Could you please add a license file to the repo to resolve this?  Thanks!

**Comment by drpebcak** [comment]
Sure, I've just added one.

**Comment by mekhanique** [comment]
Thanks!Sent from my iPhoneOn Nov 11, 2024, at 12:15 PM, Taylor Price ***@***.***> wrote:﻿
Sure, I've just added one.
